FROM ubuntu

RUN apt update && apt install -y \
    curl \
    git \
    libmagic1t64 \
    python3-pip

WORKDIR /langchain-app

COPY requirements.txt requirements.txt

RUN pip install --break-system-packages -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
