FROM nvidia/cuda:12.5.0-runtime-ubuntu22.04

RUN apt update && apt install -y \
    curl \
    git \
    libmagic1 \
    ffmpeg \
    python3-pip \
    libcudnn8 \
    libcudnn8-dev

WORKDIR /langchain-app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

ENV HF_HOME=".whisper/"

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
