version: "3"
services:

  langchain-app:
    build:
      context: langchain-app/
      dockerfile: Containerfile
    image: langchain-app
    volumes:
      - ./langchain-app/:/langchain-app/:Z
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - "label=disable"
    depends_on:
      - ollama-server
      - redis
      - mongodb

  ollama-server:
    build:
      context: ollama/
      dockerfile: Containerfile
    image: ollama-server
    ports:
      - 11434:11434
    volumes:
      - ./ollama/models:/app/models/:Z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    security_opt:
      - "label=disable" 

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/:/data/:Z
    env_file:
      - redis/.env

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db/:Z
    env_file:
      - mongodb/.env
