FROM ubuntu

RUN apt update && apt install \
    curl \
    git \
    python3-pip

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

WORKDIR /langchain

EXPOSE 8000

CMD ["python", "serve.py"]
