FROM nvidia/cuda:12.6.0-runtime-ubuntu22.04

RUN apt update && apt install -y \
    bzip2 \
    curl \
    git \
    pciutils \
    ca-certificates \
    python3-pip

WORKDIR /ollama

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN curl -fsSL https://ollama.com/install.sh | sh

ENV OLLAMA_MODELS="/app/models/"
ENV OLLAMA_HOST="0.0.0.0"
ENV OLLAMA_NUM_PARALLEL=3
ENV OLLAMA_FLASH_ATTENTION=1

EXPOSE 11434

CMD ["ollama", "serve"]
